services:
  mariadb:
    image: mariadb:latest
    container_name: gestaoatendimento
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestaoatendimento_db
    ports:
      - "3306:3306"