services:
  mariadb:
    image: mariadb:latest
    container_name: gestaounidadeatendimento
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestaounidadeatendimento_db
    ports:
      - "3307:3306"

  springboot:
    build:
      context: .
    container_name: springboot_app
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/gestaounidadeatendimento_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root