services:
  mariadb:
    image: mariadb:latest
    container_name: gestaounidadeatendimento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestaounidadeatendimento_db
    ports:
      - "3307:3306"

  app:
    image: openjdk:17-jdk
    container_name: springboot_app
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/gestaounidadeatendimento_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9090:9090"
    volumes:
      - ./target:/app
    working_dir: /app
    command: [ "java", "-jar", "gestaoatendimento-0.0.1-SNAPSHOT.jar" ]
